# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1047c1a1643177dc645980b7927d69af7b3c9fcce1dec98a5d3900e08046ac5501817e44cb7faed325cb0741875ce11659a330de05f7269439cb260ebac1c911

test:
  secret_key_base: c4aff731b20d92dbc492ef2b492805ffc322f5584a611d30e5f9614064f9ee09e158c45ec99c1537612d2fff5933938f6f4dca09abeac21f1d03b1031a6ca39e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
